kind: pipeline
name: default

steps:
- name: test
  image: golang:latest
  environment:
    LDAP_SERVER: "localhost"
    LDAP_PORT: "636"
    LDAP_BIND_DN: "uid=gitea,ou=service,dc=planetexpress,dc=com"
    LDAP_BIND_PASS: "password"
    LDAP_USER_BASE_DN: "ou=people,dc=planetexpress,dc=com"
    LDAP_USER_SEARCH_ATTR: "uid"
    LDAP_GROUP_BASE_DN: "ou=people,dc=planetexpress,dc=com"
    LDAP_GROUP_OBJECT_CLASS: "Group"
    LDAP_GROUP_SEARCH_ATTR: "member"
    LDAP_GROUP_SEARCH_FULL: "false"
    LDAP_TEST_USER: "professor"
    LDAP_TEST_PASSWORD: "professor"
  commands:
    - go test -v .
    - go vet
    - go test -race -coverprofile=coverage.txt

- name: coverage
  image: plugins/codecov
  settings: 
    token:
      from_secret: CODECOV_TOKEN
    files:
    - coverage.txt

services:
- name: openldap
  image: gitea/test-openldap:latest
  ports:
  - 389
  - 636
